CREATE VIEW Alarm_Events_View AS


SELECT 
APP_PERSON.FullName AS EmpName ,
APP_PERSON.IdentificationNo AS EmpNo,
APP_TAG.Hex AS DeviceNo,

APP_BUSINESS_RULE.Name AS EventRule,
DATEADD(HOUR,4, APP_ALARM.AlarmDate) AS EventDate,
APP_FLOOR.Name AS FloorNo,
APP_ZONE.Code AS ZoneName,

CASE
WHEN APP_ALARM.AlarmStatus = 1 THEN 'Open'
WHEN APP_ALARM.AlarmStatus = 2 THEN 'Closed'
END AS EventStatus,

APP_PRM_ALARM_CLOSURE_PROBLEM_TYPE.Name AS TriggeredTo,
APP_PRM_ALARM_CLOSURE_ACTION_TYPE.Name AS ClosureAction,
COM_USER.Name AS ClosedBy,
DATEADD(HOUR,4, APP_ALARM.ClosureDate) AS ClosureDate,
APP_ALARM.ClosureNote
FROM APP_ALARM
LEFT JOIN APP_PERSON ON APP_ALARM.EntityID=APP_PERSON.ID
LEFT JOIN APP_ENTITY_TAG_RELATION ON APP_ENTITY_TAG_RELATION.EntityID = APP_PERSON.ID AND APP_ENTITY_TAG_RELATION.Status = 1
LEFT JOIN APP_FLOOR ON APP_FLOOR.ID=APP_ALARM.FloorID
RIGHT JOIN APP_TAG ON APP_TAG.ID=APP_ENTITY_TAG_RELATION.TagID
LEFT JOIN APP_ZONE ON APP_ALARM.ZoneID=APP_ZONE.ID AND APP_ZONE.Status = 1

LEFT JOIN APP_BUSINESS_RULE ON APP_BUSINESS_RULE.ID=APP_ALARM.BusinessRuleID AND APP_BUSINESS_RULE.Status = 1


LEFT JOIN APP_PRM_ALARM_CLOSURE_PROBLEM_TYPE ON APP_PRM_ALARM_CLOSURE_PROBLEM_TYPE.Code=APP_ALARM.ClosureProblemCode
LEFT JOIN APP_PRM_ALARM_CLOSURE_ACTION_TYPE ON APP_PRM_ALARM_CLOSURE_ACTION_TYPE.Code=APP_ALARM.ClosureActionCode

LEFT JOIN COM_USER ON COM_USER.ID=APP_ALARM.ClosureUserID
